Editor/Postprocessor.cs

-   Briefly describe what this change will do
-   animation extractor folder path
-  moved define symbol add logic from Avatar Loader to core

[3602503105] animation path and postprocessor cleanup+ moved define symbol

---

~Samples/AvatarLoading/AvatarLoadingExample.cs
~Samples/AvatarLoading/AvatarLoadingExample.unity
~Samples/AvatarLod/AvatarLodExample.unity
~Samples/AvatarRender/AvatarRenderExample.cs
~Samples/AvatarRender/AvatarRenderExample.unity
~Samples/MultipleAvatarLoading/MultipleAvatarLoadingExample.cs
~Samples/MultipleAvatarLoading/MultipleAvatarLoadingExample.unity
~Samples/MultipleQualityAvatarLoading/MultipleQualityAvatarLoadingExample.cs
~Samples/MultipleQualityAvatarLoading/MultipleQualityAvatarLoadingExample.unity

- update urls used in all example scene to ensure they are valid avatars
- updated all example scenes and associated scripts to point at valid avatar urls
- open and run all example scenes in Avatar Loader module

[3619800210] update urls in examples

---

Runtime/Extras/EyeAnimationHandler.cs
Tests/Common/TestUtils.cs
Tests/Runtime/ExtrasTest.cs

- Updated avatar url, as previous one was deleted
- Commented always failing playmode test on test runner
- Added null check for when null coroutine is being stopped

Fix for various tests failing on test runner

---

.github/workflows/pr-test-runner.yml

-  On creating a PR.
-  Test runner runs.
-  Performance editmode test runs which appends load time to the `PerformanceData.json`.
-  A python script runs and it gets the data - current, avg, max, min loadtime.
-  Comment with data from previous is posted to PR.
-  The `PerformanceData.json` file is pushed to unity-sdk repo.
- A test for pushing loading of avatar loading to a json file.
- Python script for parsing json and calculating avg, max and min.
-  Test runner with running python script and adding a comment to PR
-  Observe the test runner result
-   If …

[3618026987] Add benchmark report commenting to PR 

---

Editor/DefaultSettings.cs
Editor/DefaultSettings.cs.meta
Editor/EditorAssetGenerator.cs
Editor/EditorAssetGenerator.cs.meta
Editor/ReadyPlayerMe.AvatarLoader.Editor.asmdef
Editor/UI/SettingsEditorWindow.cs
Runtime/AvatarLoaderSettings.cs
Runtime/Data/AvatarConfig.cs
Runtime/Data/AvatarContext.cs
Runtime/Data/AvatarMetadata.cs
Runtime/Data/AvatarMorphTarget.cs
Runtime/Data/AvatarRenderSettings.cs
Runtime/Data/AvatarUri.cs
Runtime/Data/CustomEventArgs.cs
Runtime/Data/CustomException.cs
Runtime/Data/Enums.cs
Runtime/Utils/AvatarCache.cs
Runtime/Utils/AvatarConfigMap.cs
Runtime/Utils/AvatarConfigProcessor.cs
Runtime/Utils/AvatarEventArgs.cs
Tests/Editor/AvatarAPITests.cs
Tests/Editor/AvatarLoaderTests.cs
Tests/Runtime/ExtrasTest.cs

-  Namespaces
- Generation of AvatarLoaderSettings
- Test it in empty project by importing core with branch 
```
"com.readyplayerme.core": "https://github.com/readyplayerme/Unity-Core.git#bugfix/namespace-fix"
```

[3660211586] Fix namespaces

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md

-   ADded contribution docs (same as from Core module but with a few updates 
-   Contribution.md and Issue templates

[3651634299] chore: added contribution docs from Core

---

Runtime/AvatarLoaderSettings.cs
Runtime/Operations/GltFastGameObjectInstantiator.cs

- Adapted gltf fast api usage according to v5
- Fixed space in new AvatarLoaderSettings scriptable object 
-  Will work with PR https://github.com/readyplayerme/Unity-SDK/pull/19

[3484650875] Adapt API according to gltfast v5

---

Shaders/glTFastShaderVariantsURP.shadervariants

-   added missing shader variant required for URP builds
-   ShaderVariantsURP
-   open in a URP project and build, check that loading an avatar works without errors

[3841829141] added missing shader variant for URP

---

.github/CODEOWNERS

-   added CODEOWNERS file for automatic PR reviewers
-   added codeowners file

[2919913072] feat: add codeowners

---

Editor/ShaderVariantHelper.cs
Editor/UI/EditorWindows/SettingsEditorWindow.cs

-   Added setting either enable or disable the RPM logger in RPM Settings window under "Other" section. It uses a "ProjectPref" to keep its state in between sessions.
- also some minor cleanup and refactoring
-   SDK logging enabled setting to settings window

[3739587991] feature/optional sdk logging

---

.github/latest.md
.github/workflows/auto-release-action.yml

-   git action for automatic release creation when tag is pushed
-   git action for automatic release creation

[3853039729] Feature/auto release action

---

Runtime/Data/AvatarConfig.cs
Runtime/Data/Enums.cs
Runtime/Utils/AvatarConfigProcessor.cs

-   Added texture channel in AvatarConfig, which lets one select texture to be included in avatar.
- TextureChannel in AvatarConfig
-  Try experiment with AvatarConfig with different sets of texture channel selected

[3631444741] Add texture channel in AvatarConfig 

---

LICENSE.md
package.json

-   Update LICENSE url
-   Update LICENSE url
- 

Update LICENSE url

---

Samples~/MultipleAvatarRender.meta
Samples~/MultipleAvatarRender/MultipleAvatarRenderExample.cs
Samples~/MultipleAvatarRender/MultipleAvatarRenderExample.cs.meta
Samples~/MultipleAvatarRender/MultipleAvatarRenderExample.unity
Samples~/MultipleAvatarRender/MultipleAvatarRenderExample.unity.meta

- Example with scripts and scene for different render configs
- Add the sample by removing ~ from the end of sample folder
- Run the multiple render example scene

[3211509902] Add multiple render example

---

Editor/Postprocessor.cs

-   Updated the animation folder path to something more appropriate. 
- also removed the define symbol conditional
-  animation post processer and file path

[4089805810] updated animation folder path

---

Runtime/Extras/EyeAnimationHandler.cs
Runtime/Extras/VoiceHandler.cs
Runtime/Utils/AvatarBoneHelper.cs
Runtime/Utils/AvatarBoneHelper.cs.meta
Runtime/Utils/ExtensionMethods.cs

-   added extra log warning for missing blendshapes on extra's scripts
- also some general refactoring
-    extra log warning for missing blendshapes on extra's scripts
-   refactored VoiceHandler and EyeAnimationhandler

[SDK-41] Feature/log missing blendshapes

---

Tests/Editor/AvatarAPITests.cs
Tests/Editor/AvatarLoaderTests.cs
Tests/Editor/HelperTests.cs

-  Cleanup for tests
-  Run tests
[SDK-136]: https://ready-player-me.atlassian.net/browse/SDK-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-136] Add cleanup for some tests

---

.github/pull_request_template.md
.github/workflows.meta
.github/workflows/pr-test-runner.yml
.github/workflows/update-unity-sdk.yml
Runtime/Extras/EyeAnimationHandler.cs
Runtime/Extras/VoiceHandler.cs
Runtime/Utils/ExtensionMethods.cs

```Package
Core: develop
```
- This update the pr-template with dependency - core branch
- Also updates test runner to checkout defined avatar loader branch in PR.
- Action for updating avatar loader in unity sdk
- Test runner action to checkout avatar loader specified branch
- Replace remainingcoroutine with async
-  Coroutine extension
- The branch checkout seems to be working as visible in GitHub action run
- Android and iOS build test to check voice handler and eye animation shift to async from coroutine
-   If more details are necessary to support the …

[SDK-138] Add checkout of core branch

---

Editor/UI/EditorWindows/SettingsEditorWindow.cs
Editor/UI/Helpers/AvatarConfigFields.cs
Runtime/Operations/UrlProcessor.cs
Tests/Editor/AvatarUriProcessTests.cs

-   Add spacing and fixed clipping issues
- Core settings and avatar loader window UI updates

 fixed alignment and element spacing on Core settings window

---

Editor/UI/EditorWindows/SetupGuideWindow.cs
Editor/UI/SetupGuidePanels/AnalyticsPanel.cs

```Package
Core: feature/setup-guide-fix
```
-   small refactor of project prefs
-   List your additions and new features here.
-   small refactor of logic to work with updated project prefs from core
[SDK-185]: https://ready-player-me.atlassian.net/browse/SDK-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-185] fix: refactored project pref

---

.github/pull_request_template.md
Editor/AvatarConfigEditor.cs
Editor/UI/AvatarConfigEditor.meta
Editor/UI/AvatarConfigEditor/AvatarConfigEditor.uxml
Editor/UI/AvatarConfigEditor/AvatarConfigEditor.uxml.meta
Editor/UI/AvatarConfigEditor/AvatarConfigNewEditor.cs
Editor/UI/AvatarConfigEditor/AvatarConfigNewEditor.cs.meta

```Package
Core: develop
```
-  Avatar config inspector using UI Toolkit
- Check avatar config scriptable object, change values and observe if those change persist. 
- Also load avatar by using them in runtime and editor.
[SDK-187]: https://ready-player-me.atlassian.net/browse/SDK-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-187] Add avatar config inspector using UI toolkit

---

Editor/UI/EditorWindows/SetupGuide/SetupGuide.uxml
Runtime/Operations/AvatarDownloader.cs
Runtime/Operations/AvatarRenderDownloader.cs
Runtime/Operations/MetadataDownloader.cs
Runtime/Utils/WebRequestDispatcherExtension.cs

```Package
Core: develop
```
- Fixed showing of correct failure type exception when no internet exception is thrown
- Fixed setup guide window width.
- Disable internet and load avatar 
- Open setup guide window and try expanding it.
[SDK-194]: https://ready-player-me.atlassian.net/browse/SDK-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-194] Fix exception throw for no internet connection

---

Editor/UI/EditorWindows/AvatarLoaderEditor/AvatarLoaderEditor.cs
Editor/UI/EditorWindows/AvatarLoaderEditorWindow.cs
Editor/UI/EditorWindows/SettingsWindow/SettingsEditor.cs
Runtime/AvatarObjectLoader.cs
Runtime/Data/AvatarContext.cs
Runtime/Operations/AvatarDownloader.cs
Runtime/Operations/AvatarProcessor.cs
Runtime/Operations/MetadataDownloader.cs
Runtime/Operations/UrlProcessor.cs
Runtime/Utils/AvatarCache.cs
Runtime/Utils/ExtensionMethods.cs
Tests/Editor/AvatarUriProcessTests.cs
Tests/Editor/MetadataDownloadTests.cs

```Package
Core: feature/cache-refactor
```
-   this PR includes refactoring and a number of proposed improvements for avatar caching
- with these changes, avatar caching will now work exactly the same in editor and on builds
- some functions are now more simplified as a result. 
-   List your additions and new features here.
-   List your updates and changes here.
[SDK-195]: https://ready-player-me.atlassian.net/browse/SDK-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SDK-195] refactor avatar caching

---

.github/latest.md
Editor/UI/EditorWindows/SetupGuideWindow.cs
package.json

```Package
Core: hotfix/1.3.3
```
-   fix for setup guide
-   setup guide first time window display

fix: update first open logic to show setup guide 

---

.github/latest.md
Editor/UI/EditorWindows/SetupGuideWindow.cs
package.json

```Package
Core: hotfix/1.3.3
```
-   This change includes a fix for an issue that caused the log project open and identify user events being fired every time unity recompiles
-   List your additions and new features here.
-   List your updates and changes here.

[SDK-219] fix: move project open events and improve logic

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
README.md

```Package
Core: branch
```
-   adding deprecation notice in readme and git templates
-   List your additions and new features here.
-   List your updates and changes here.

[SDK-311] Feature/deprecation
